# Config file for executing policy_gradient.py
# for yml syntax, see https://en.wikipedia.org/wiki/YAML#Design
# install with: pip install PyYAML
# IMPORTANT: scientific float notation needs a dot otherwise it gets interpreted as a string
# incorrect: 1e-3, correct: 1.e-3

# create convolutional structure instead of regular neural network
cnn_on: true
# every how many games to do a parameter update?
batch_size: 100
# learning rate
learn_rate: 1.e-3
# after how many games to print the results
print_results_every: 100
# path to save a network file (can be same as load_network_file_path)
save_network_file_path: networks/test/net.p
# path to load a network file (change to continue training existing network, none otherwise)
load_network_file_path: none

# total number of games to train
number_of_games: 300

# structure of regular neural network
hidden_layers: !!python/tuple [90, 90, 90]

# structure of convolutional neural network
number_of_cnnlayers: 3
filter_shape: [3, 3] # Length and width of filter
filter_depth: 100 # How different 'features' are we trying to learn
dense_width: [] # Number of nodes in layers after the CNN